Repository RUC-MSc-CS-CIT-2024/portfolio_subproject_1, pull requests merged in 2024-10, with the labels that each got.

#27 feat: persons population script
  src/B2_build_movie_db.sql
  src/populate_persons.sql
Labels: Feature

#24 feat: build function to rate media
  src/D_functions_and_procedures.sql
Labels: Feature

#29 feat: framework population script, to provide some dummy data.
  src/framework_population_script.sql
Labels: Feature

#26 feat: structure_string_search function
  README.md
  src/B2_build_movie_db.sql
  src/D_functions_and_procedures.sql
  src/core_data_transform.sql
Labels: Feature

#36 feat: build view and function to find the most frequent co-actors
  src/D_functions_and_procedures.sql
Labels: Feature

#34 feat: D8 added - List Actors by Popularity - List Co-Actors by Popula…
  src/D_functions_and_procedures.sql
Labels: Feature

#40 feat: build function to retrieve words associated with a person
  src/D_functions_and_procedures.sql
Labels: Feature

#42 feat: build a function to find titles that match the exact-match querying
  src/D_functions_and_procedures.sql
Labels: Feature

#46 feat: build function to best match querying
  src/D_functions_and_procedures.sql
Labels: Feature

#33 feat: D7 name rating functionality
  src/B2_build_movie_db.sql
  src/D_functions_and_procedures.sql
Labels: Feature

#25 docs: ER_diagram_design
  ER_diagram_handmade.drawio.svg
Labels: documentation

#53 feat: Indexing
  src/D_functions_and_procedures.sql
Labels: Optimization

#55 Feature/basic framework functionality
  src/C2_build_framework.sql
  src/D_functions_and_procedures.sql
Labels: Feature

#49 feat: build function for word to word querying
  src/D_functions_and_procedures.sql
Labels: Feature

#64 feat: set up review text and use data correct in test
  src/D_functions_and_procedures.sql
Labels: Feature

#60 feat: return the title for the functions
  src/D_functions_and_procedures.sql
Labels: Feature

#69 feat: added test_functions.sql to test all functions and procedures.
  src/B2_build_movie_db.sql
  src/D_functions_and_procedures.sql
  src/test_functions.sql
Labels: Feature

#71 fix: structured_string_search function
  src/B2_build_movie_db.sql
  src/D_functions_and_procedures.sql
Labels: bugfix

#75 Feature/test script update
  src/test_functions.sql
  src/test_output_file.txt
Labels: Optimization
